export const GET_CHANNELS = "GET_CHANNELS"
export const GET_CHANNELS_SUCCESS = "GET_CHANNELS_SUCCESS"
export const GET_CHANNELS_FAIL = "GET_CHANNELS_FAIL"
export const INTIGRATE_NEW_CHANNEL = "INTIGRATE_NEW_CHANNEL"
export const INTIGRATE_NEW_CHANNEL_SUCCESS = "INTIGRATE_NEW_CHANNEL_SUCCESS"
export const INTIGRATE_NEW_CHANNEL_FAIL = "INTIGRATE_NEW_CHANNEL_FAIL"


